# Generated by Django 5.0.4 on 2024-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='count',
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
